export var langEn = {
    play: 'Play',
    next: 'Next',
    drawCart: 'Draw a cart',
    stand: 'Stand',
    enterNumber: "Please, enter a number",
    tooSmallBid: "Too small bet",
    notEnoughMoney: "You have not enough money",
    loseTryAgain: "You lost. Can you try again??",
    exceedLimit: "Exceed limit 21.",
    win : 'Congratulation, you won!',
    draw : "Draw",
    lose : 'Opponent won',
    cash : 'Cash',
    setBet : 'Enter your bet',
    bet : 'Bet',
    cartValue : 'Value of cart',
    opponentCartValue : 'Value of opponent cart',
}